# BUILD & RUN COMMANDS:
# ---------------------
# ATTENTION: The build commands should be launched being in this project root directory.
#
# To rebuild the image with removal of the previous build:
#   docker rmi developmentrunsk/fajnpython:3.14 --force && docker build --pull --no-cache -t developmentrunsk/fajnpython:3.14 -f Dockerfile.fajnpython3.14 .
#
# To redirect all build output to build.log file:
#   docker rmi developmentrunsk/fajnpython:3.14 --force && > build.log && docker build --pull --no-cache -t developmentrunsk/fajnpython:3.14 -f Dockerfile.fajnpython3.14 . > build.log 2>&1
#
# To run the image in interactive mode:
#   docker run -it developmentrunsk/fajnpython:3.14 /bin/bash
#
# PUBLISH ON DOCKERHUB:
# ---------------------
# To push the image to https://hub.docker.com/r/developmentrunsk/fajnpython:
#   docker login
#   docker push developmentrunsk/fajnpython:3.14
#   docker logout
# 
# IMAGES, CONTAINERS & VOLUMES INFO COMMANDS:
# -------------------------------------------
# To list all images (without intermediate ones which does not spend dick space):
#   docker image ls
# 
# To list all images (even with intermediate ones):
#   docker image ls --all
# 
# To list all containers (even with temporary ones which are preserved even after 
# they are stopped, see https://stackoverflow.com/a/56537550/1245149):
#   docker container ls --all --size
# 
# To list all volumes:
#   docker volume ls
# 
# To find size of all volumes inspect some of volumes at first to find a path to all volumes directories
# and then use `du` (disk usage) to find out spent disk spage (e.g. for docker volumes on linux):
#   docker volume inspect <volume_name>
#   sudo du -sh /var/lib/docker/volumes/
# Or for given <volume_name>:
#   sudo du -sh /var/lib/docker/volumes/<volume_name>
# 
# IMAGES, CONTAINERS & VOLUMES CLEANUP COMMANDS:
# ----------------------------------------------
# To clean up disk space remove at first temporary containers (otherwise their existence 
# will block removal of dangling images) and then remove dangling images:
#   docker container prune
#   docker image prune
# 
# To remove all unused images (not just the dangling ones):
#   docker image prune --all
# 
# To remove an image by its id:
#   docker image rm <image_id>
#
# ATTENTION: Be careful with volumes removal (and DO NOT USE at all `docker volume prune` which
# removes all ACTUALLY unused volumes) because very probably you will lost your data (mostly some databases).
# Images and containers are easily reproducible (building from Dockerfile or cloning from hub.docker.com),
# but this is not the case of volumes.
#
# To remove an volume by its name:
#   docker volume rm <volume_name>
FROM mcr.microsoft.com/devcontainers/python:2-3.14-trixie

# Use the vscode user to run the container
USER vscode

# Create directory for VS Code Server data (e.g. augment code threads)
# to preserve them even after the container is rebuild
# NOTE: It is created here explicitly to ensure it has `vscode` as owner.
# Otherwise it would be created with `root` as owner because it is mapped to named volume in docker-compose.yml.
RUN mkdir -p /home/vscode/.vscode-server
